# Server configurations
server:
  host: localhost
  port: 8083

# Database credentials
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  name: poc

# Kafka configuration
kafka:
  url: localhost:9092
  flushFrequencyMs: 500
  topics:
    orderPlaced: 'order-placed'
    itemsReserved: 'items-reserved'
    paymentProcessed: 'payment-processed'
    txnError: 'txn-error'

    inventoryUpdateRequest: 'inventory-update-request'
    inventoryUpdateStatus: 'inventory-update-status'
    paymentRequest: 'payment-request'
    paymentStatus: 'payment-status'

    orderStatus: 'order-status'