# 0 - choreography
# 1 - orchestration
application:
  mode: 1

# Server configurations
server:
  host: localhost
  port: 8082

# Database credentials
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  name: poc

# Kafka configuration
kafka:
  url: localhost:9092
  flushFrequencyMs: 500
  topics:
    itemsReserved: 'items-reserved'
    paymentProcessed: 'payment-processed'
    paymentRequested: 'payment-requested'
    paymentStatus: 'payment-status'
    txnError: 'txn-error'