# Use the official Go image as the base image
FROM golang:1.19 AS build

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

RUN ls

RUN go build -o paymentsservice

EXPOSE 8082

RUN ls

CMD ./paymentsservice